# Site settings
title: Persoonlijke blog # site title
description: >- # site description
  He's writing in Bahasa about web technology and experience as a journal 
  for documentation things that he learned, meet him <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: nl-NL # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/images/AntiWEF.webp # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Persoonklijke Blog # author name
  bio: >- # tell to the world
    Gemaakt en ontworpen om mijn gedachtes te kunnen uiten.
    Je kunt direct contact met me opnemen via <a href='mailto:persoonlijkeblog@privemail.xyz' style="color: #00FF5D" target='_blank'>mail</a>. 
    Foreigners, check  <a href='https://www-persoonlijkeblog-nl.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=nl&_x_tr_pto=wapp' style="color: #FF0000" target='_blank'>here for translation 🏴󠁧󠁢󠁥󠁮󠁧󠁿</a>
    
  #username: username # general username
  #github: github_username # github username
  #twitter: twitter_username # twitter username
  #facebook: facebook_username # facebook username
  #email: persoonlijkeblog@privemail.xyz # email adress
  avatar: assets/images/AntiWEF.webp # change with your own avatar

# URL settings
url: "https://persoonlijkeblog.nl" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
